### ISSUE TITLE
Error when upload large file

### ISSUE THREAD

**Issue by InfoO2** [doerffler/flysystem-onedrive#9]
This error appear when I tried to upload large file
`local.ERROR: Call to undefined method Illuminate\Support\Facades\Http::put() {"userId":1,"exception":"[object] (Error(code: 0): Call to undefined method Illuminate\\Support\\Facades\\Http::put() at C:\\xampp\\htdocs\\system\\vendor\\justus\\flysystem-onedrive\\src\\OneDriveAdapter.php:206)`

**Comment by Jusdon** [comment]
Fixed in v2.0.5
